namespace SpriteKind {
    export const teleporter = SpriteKind.create()
    export const teleporteur = SpriteKind.create()
    export const objectif = SpriteKind.create()
    export const enemy2 = SpriteKind.create()
    export const tuile = SpriteKind.create()
    export const object = SpriteKind.create()
    export const épé = SpriteKind.create()
    export const mappoint = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.teleporteur, function (sprite, otherSprite) {
    game.showLongText("Zarlenem tu-es ou bon sens", DialogLayout.Full)
    tiles.setCurrentTilemap(tilemap`niveau4`)
    sprites.destroyAllSpritesOfKind(SpriteKind.object)
    tiles.placeOnTile(Arlem, tiles.getTileLocation(2, 2))
    Zarlenem = sprites.create(img`
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ......aaaa........................
        ......faaaa.......................
        ......ffffaa......................
        ..222.fffffaa.....................
        .22222ffffffaa....................
        .22222ffffffaaaaaaaaaaaaaa........
        .22222fffffffffffffffffffaa.......
        .22222dfffffffffffffffffffa.......
        222222dfffffffffffffffffffa.......
        222222dfffffffffffffffffffafaaaaa1
        222ddddfffffffffffffffffffaffffff1
        .22...fffafffffaffffffffffaffffff1
        ......fffafffffaffffffffffaffffff1
        ......fffa..fffa......ffffa.......
        ......fffa..fffa......ffffaaaaaaa1
        ......fffa..dddd......fffffffffff1
        ......dddd..dddd......fffffffffff1
        ......dddd.............ffffffffff1
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        `, SpriteKind.enemy2)
    tiles.placeOnTile(Zarlenem, tiles.getTileLocation(29, 31))
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, Arlem)
    Arlem.setImage(img`
        . . . . e e e e e . . 
        . . . 2 2 e e e e . . 
        . . 2 2 2 2 e 2 e . . 
        . . 2 2 2 2 2 d 2 2 . 
        . . a 2 2 2 d 8 d . . 
        . . a 2 d d d d d . . 
        . . a 2 d d d d d . . 
        . . a f f f f f f . . 
        . a a f f f f f f . . 
        . a a f f f f f f . . 
        . 9 8 f f a f f f . . 
        . 9 8 f f a f f f . . 
        . 9 8 f f a f f f . . 
        . 9 8 f f a f f f . . 
        . a a f f a f f f . . 
        . 9 8 f f d d d f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 8 8 . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . 1 1 1 1 . . . 
        `)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.enemy2, function (sprite, otherSprite) {
    game.showLongText("vaaaaaaaaaa tttttt'eeeeennnnn aaaaahhhhhhhhhhhhhhhhhhhhh", DialogLayout.Top)
    Zarlenem.setImage(img`
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ......aaaa........................
        ......faaaa.......................
        ......ffffaa......................
        ..222.fffffaa.....................
        .22222ffffffaa....................
        .22222ffffffaaaaaaaaaaaaaa........
        .22222fffffffffffffffffffaa.......
        .22222dfffffffffffffffffffa.......
        222222dfffffffffffffffffffa.......
        222222dfffffffffffffffffffafaaaaa1
        222ddddfffffffffffffffffffaffffff1
        .22...fffafffffaffffffffffaffffff1
        ......fffafffffaffffffffffaffffff1
        ......fffa..fffa......ffffa.......
        ......fffa..fffa......ffffaaaaaaa1
        ......fffa..dddd......fffffffffff1
        ......dddd..dddd......fffffffffff1
        ......dddd.............ffffffffff1
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        `)
    game.showLongText("Qu'est-ce qui ce passe!", DialogLayout.Bottom)
    game.showLongText("Zarlenem!!", DialogLayout.Bottom)
    Zarlenem.setImage(img`
        ..................................
        .............eee..................
        ............e222eee...............
        ............2222222e..............
        .............d22222e..............
        .............d22222e..............
        .............d22222e..............
        .............dddddd...............
        .............fffffa...............
        .............fffffa...............
        .............fffffa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fdddfa...............
        .............fffffa...............
        .............fffffa...............
        .............fffffa...............
        .............fffffa...............
        ..............ffffafaaaa1.........
        ..............ffffafffff1.........
        ..............ffffafffff1.........
        ..............ffffafffff1.........
        ..............ffffa...............
        ..............ffffaaaaaa1.........
        ..............ffffffffff1.........
        ..............ffffffffff1.........
        ...............fffffffff1.........
        ..................................
        `)
    game.showLongText("euh Zarlenem?", DialogLayout.Bottom)
    Zarlenem.setImage(img`
        ..................................
        .............eee..................
        ............e222eee...............
        ............2222222e..............
        .............d22222e..............
        .............d22222e..............
        .............d22222e..............
        .............dddddd...............
        .............fffffa...............
        .............fffffa...............
        .............fffffa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fdddfa...............
        .........fffffffffa...............
        ........ffffffffffa...............
        ........ffffffffffa...............
        ........ffffffffffa...............
        ........ffffffffffffaaaa1.........
        ........ffff..ffffffffff1.........
        ........ffff..ffffffffff1.........
        ........ffff..ffffffffff1.........
        ........1111...fffffffff1.........
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        `)
    game.showLongText("Qu'est-ce qu t'arrive", DialogLayout.Bottom)
    Zarlenem.setImage(img`
        ..................................
        .............eee..................
        ............e222eee...............
        ............2222222e..............
        .............d22222e..............
        .............d22222e..............
        .............d22222e..............
        .............dddddd...............
        .............fffffa...............
        .............fffffa...............
        .............fffffa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fffafa...............
        .............fdddfa...............
        .............fffffa...............
        .............fffffa...............
        .............fffffa...............
        .............fffffa...............
        ..............fffa................
        ..............fffa................
        ..............fffa................
        ..............fffa................
        ..............fffa................
        ..............fffa................
        ..............fffa................
        ..............1111................
        ..................................
        ..................................
        `)
    game.showLongText("répond moi bon sens!", DialogLayout.Bottom)
    Zarlenem.setImage(img`
        ........eeee...
        ...e8e8ee88e8..
        ...ee8ee8ee8e..
        ...8ee88eeeee..
        ...ee88d669e...
        ...ec99d696e...
        ...e8ddddd66...
        ...8edcddd6e...
        ..8fccffff66...
        ..fffccccf6ff..
        .fffffcfff6fff.
        fffffffcf66ffff
        9ffffffcffff66f
        9999fcffccfff6f
        fff9fcfffcffff6
        ffffccfffcfffff
        ffffcfffff88ff6
        ffffccfffff88ff
        ffffffccfff8fff
        fffffffc8888fff
        989ffff88fffddd
        ...fff88f66f...
        ...ff88fff6f...
        ...ff8ffff6f...
        ...f88...f6f...
        ...f8f...66f...
        ...fff...66f...
        ...fff...f66...
        ...fff...ff6...
        ...fff...ff6...
        ...222...222...
        `)
    tiles.placeOnTile(Zarlenem, tiles.getTileLocation(31, 30))
    statusbar = statusbars.create(20, 4, StatusBarKind.Health)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.object, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.UntilDone)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Arlem,
    [img`
        ...................
        .......22eee.......
        .....2222eeeee.....
        ....22222eeeeee....
        ...222222222eeee...
        ...2222222dd22ee...
        ...222228dd88dee...
        ...222288dd88d2e...
        9992222dddddddd2...
        969a2dddddddddd....
        999aadddffffddd....
        .aaaadddddddddd....
        ..aaffffffffffff...
        ..affffffffffffff..
        ..ffffffffffffffff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..dddffffffffffaff.
        .....ffffffffffddd.
        .....afff..faff889.
        .....aff....aff8889
        .....aff....aff9889
        .....aff....aff.999
        .....aff....aff....
        .....aff....aff....
        .....aff....111....
        .....111...........
        `,img`
        .......22eee.......
        .....2222eeeee.....
        ....22222eeeeee....
        ...222222222eeee...
        ...2222222dd22ee...
        ...222228dd88dee...
        ...222288dd88d2e...
        9992222dddddddd2...
        969a2dddddddddd....
        999aadddffffddd....
        .aaaadddddddddd....
        ..aaffffffffffff...
        ..affffffffffffff..
        ..ffffffffffffffff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..dddffffffffffaff.
        .....ffffffffffaff.
        .....ffffffffffddd.
        .....afffffffff889.
        .....afff..faff8889
        .....aff....aff9889
        .....aff....aff.999
        .....aff....aff....
        .....aff....111....
        .....aff...........
        .....aff...........
        .....111...........
        `,img`
        .......22eee.......
        .....2222eeeee.....
        ....22222eeeeee....
        ...222222222eeee...
        ...2222222dd22ee...
        ...222228dd88dee...
        ...222288dd88d2e...
        9992222dddddddd2...
        969a2dddddddddd....
        999aadddffffddd....
        .aaaadddddddddd....
        ..aaffffffffffff...
        ..affffffffffffff..
        ..ffffffffffffffff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..dddffffffffffaff.
        .....ffffffffffddd.
        .....afffffffff889.
        .....afff..faff8889
        .....aff....aff9889
        .....aff....aff.999
        .....aff....aff....
        .....aff....aff....
        .....aff....aff....
        .....aff....111....
        .....111...........
        `,img`
        ...................
        .......22eee.......
        .....2222eeeee.....
        ....22222eeeeee....
        ...222222222eeee...
        ...2222222dd22ee...
        ...222228dd88dee...
        ...222288dd88d2e...
        9992222dddddddd2...
        969a2dddddddddd....
        999aadddffffddd....
        .aaaadddddddddd....
        ..aaffffffffffff...
        ..affffffffffffff..
        ..ffffffffffffffff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..dddffffffffffddd.
        .....afff..faff889.
        .....aff....aff8889
        .....aff....aff9889
        .....aff....aff.999
        .....aff....aff....
        .....aff....aff....
        .....aff....aff....
        .....111....111....
        `,img`
        .......22eee.......
        .....2222eeeee.....
        ....22222eeeeee....
        ...222222222eeee...
        ...2222222dd22ee...
        ...222228dd88dee...
        ...222288dd88d2e...
        9992222dddddddd2...
        969a2dddddddddd....
        999aadddffffddd....
        .aaaadddddddddd....
        ..aaffffffffffff...
        ..affffffffffffff..
        ..ffffffffffffffff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffddd.
        ..dddffffffffff89..
        .....afffffffff889.
        .....afff..faff8889
        .....aff....aff9889
        .....aff....aff.999
        .....aff....aff....
        .....aff....aff....
        .....aff....aff....
        .....111....aff....
        ............111....
        `,img`
        .......22eee.......
        .....2222eeeee.....
        ....22222eeeeee....
        ...222222222eeee...
        ...2222222dd22ee...
        ...222228dd88dee...
        ...222288dd88d2e...
        9992222dddddddd2...
        969a2dddddddddd....
        999aadddffffddd....
        .aaaadddddddddd....
        ..aaffffffffffff...
        ..affffffffffffff..
        ..ffffffffffffffff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffddd.
        ..affffffffffff9...
        ..dddffffffffff89..
        .....afffffffff889.
        .....afff..faff8889
        .....aff....aff9889
        .....aff....aff.999
        .....aff....aff....
        .....111....aff....
        ............aff....
        ............aff....
        ............111....
        `,img`
        .......22eee.......
        .....2222eeeee.....
        ....22222eeeeee....
        ...222222222eeee...
        ...2222222dd22ee...
        ...222228dd88dee...
        ...222288dd88d2e...
        9992222dddddddd2...
        969a2dddddddddd....
        999aadddffffddd....
        .aaaadddddddddd....
        ..aaffffffffffff...
        ..affffffffffffff..
        ..ffffffffffffffff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffddd.
        ..dddffffffffff89..
        .....afffffffff889.
        .....afff..faff8889
        .....aff....aff9889
        .....aff....aff.999
        .....aff....aff....
        .....aff....aff....
        .....111....aff....
        ............aff....
        ............111....
        `],
    110,
    controller.down.isPressed()
    )
})
controller.up.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, Arlem)
    Arlem.setImage(img`
        ......22eeeee......
        .....222eeeeee.....
        ....2222eeeeeee....
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        999.22222eeeeee....
        969af22222eeeee....
        999aff222222eee....
        .aaaafffffffffff...
        ..faae9ffffffffff..
        ..ffe889ffffffffff.
        ..aff8889fffffffff.
        ..afff8889fffffaff.
        ..affff8889ffffaff.
        ..afffff8889fffaff.
        ..affffff8889ffaff.
        ..afffffff8889faff.
        ..dddffffff888addd.
        .....fffffff8aaaf..
        .....afff..ffaaa9..
        .....aff....afa889.
        .....aff....aff8889
        .....aff....aff.989
        .....aff....aff..99
        .....aff....aff....
        .....aff....aff....
        .....111....111....
        `)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    myMinimap = minimap.minimap(MinimapScale.Original, 0, 1)
    minimap.includeSprite(myMinimap, Arlem)
    mapSprite.setImage(minimap.getImage(myMinimap))
    pause(1000)
    sprites.destroy(mapSprite)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Arlem,
    [img`
        ...................
        ......22eeeee......
        .....222eeeeee.....
        ....2222eeeeeee....
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        999.22222eeeeee....
        969af22222eeeee....
        999aff222222eee....
        .aaaafffffffffff...
        ..faae9ffffffffff..
        ..ffe889ffffffffff.
        ..aff8889ffffffaff.
        ..afff8889fffffaff.
        ..affff8889ffffaff.
        ..afffff8889fffaff.
        ..affffff8889ffaff.
        ..dddfffff8889faff.
        .....ffffff888addd.
        .....afff..f8aaa...
        .....aff....faaa9..
        .....aff....afa889.
        .....aff....aff9889
        .....aff....aff.989
        .....aff....aff..99
        .....aff....111....
        .....111...........
        `,img`
        ......22eeeee......
        .....222eeeeee.....
        ....2222eeeeeee....
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        999.22222eeeeee....
        969af22222eeeee....
        999aff222222eee....
        .aaaafffffffffff...
        ..faae9ffffffffff..
        ..ffe889ffffffffff.
        ..aff8889ffffffaff.
        ..afff8889fffffaff.
        ..affff8889ffffaff.
        ..afffff8889fffaff.
        ..dddffff8889ffaff.
        .....fffff8889faff.
        .....ffffff888addd.
        .....affffff8aaa...
        .....afff..ffaaa9..
        .....aff....afa889.
        .....aff....aff9889
        .....aff....aff.989
        .....aff....111..99
        .....aff...........
        .....aff...........
        .....111...........
        `,img`
        ......22eeeee......
        .....222eeeeee.....
        ....2222eeeeeee....
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        999.22222eeeeee....
        969af22222eeeee....
        999aff222222eee....
        .aaaafffffffffff...
        ..faae9ffffffffff..
        ..ffe889ffffffffff.
        ..aff8889ffffffaff.
        ..afff8889fffffaff.
        ..affff8889ffffaff.
        ..afffff8889fffaff.
        ..affffff8889ffaff.
        ..dddfffff8889faff.
        .....ffffff888addd.
        .....affffff8aaa...
        .....afff..ffaaa9..
        .....aff....afa889.
        .....aff....aff9889
        .....aff....aff.989
        .....aff....aff..99
        .....aff....aff....
        .....aff....111....
        .....111...........
        `,img`
        ...................
        ......22eeeee......
        .....222eeeeee.....
        ....2222eeeeeee....
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        999.22222eeeeee....
        969af22222eeeee....
        999aff222222eee....
        .aaaafffffffffff...
        ..faae9ffffffffff..
        ..ffe889ffffffffff.
        ..aff8889ffffffaff.
        ..afff8889fffffaff.
        ..affff8889ffffaff.
        ..afffff8889fffaff.
        ..affffff8889ffaff.
        ..afffffff8889faff.
        ..dddffffff888addd.
        .....afff..f8aaa...
        .....aff....faaa9..
        .....aff....afa8899
        .....aff....aff9889
        .....aff....aff.989
        .....aff....aff..9.
        .....aff....aff....
        .....111....111....
        `,img`
        ......22eeeee......
        .....222eeeeee.....
        ....2222eeeeeee....
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        999.22222eeeeee....
        969af22222eeeee....
        999aff222222eee....
        .aaaafffffffffff...
        ..faae9ffffffffff..
        ..ffe889ffffffffff.
        ..aff8889ffffffaff.
        ..afff8889fffffaff.
        ..affff8889ffffaff.
        ..afffff8889fffaff.
        ..affffff8889ffaff.
        ..afffffff8889fddd.
        ..dddffffff888a....
        .....affffff8aaa...
        .....afff..ffaaa9..
        .....aff....afa889.
        .....aff....aff9889
        .....aff....aff.989
        .....aff....aff..99
        .....aff....aff....
        .....111....aff....
        ............111....
        `,img`
        ......22eeeee......
        .....222eeeeee.....
        ....2222eeeeeee....
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        999.22222eeeeee....
        969af22222eeeee....
        999aff222222eee....
        .aaaafffffffffff...
        ..faae9ffffffffff..
        ..ffe889ffffffffff.
        ..aff8889ffffffaff.
        ..afff8889fffffaff.
        ..affff8889ffffaff.
        ..afffff8889fffaff.
        ..affffff8889ffddd.
        ..afffffff8889f....
        ..dddffffff888a....
        .....affffff8aaa...
        .....afff..ffaaa9..
        .....aff....afa889.
        .....aff....aff9889
        .....aff....aff.989
        .....111....aff..99
        ............aff....
        ............aff....
        ............111....
        `,img`
        ......22eeeee......
        .....222eeeeee.....
        ....2222eeeeeee....
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        ...22222eeeeeeee...
        999.22222eeeeee....
        969af22222eeeee....
        999aff222222eee....
        .aaaafffffffffff...
        ..faae9ffffffffff..
        ..ffe889ffffffffff.
        ..aff8889ffffffaff.
        ..afff8889fffffaff.
        ..affff8889ffffaff.
        ..afffff8889fffaff.
        ..affffff8889ffaff.
        ..afffffff8889fddd.
        ..dddffffff888a....
        .....affffff8aaa...
        .....afff..ffaaa9..
        .....aff....afa889.
        .....aff....aff9889
        .....aff....aff.989
        .....aff....aff..99
        .....aff....aff....
        .....111....aff....
        ............111....
        `],
    110,
    controller.up.isPressed()
    )
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    épé_Arlem = sprites.create(img`
        . . . . . . . 9 9 9 . . . . . . . . . . . . . . 
        . . . . . . . 9 6 9 . . . . . . . . . . . . . . 
        . . . . . . . 9 9 9 . . . . . . . . . . . . . . 
        . . . . . . . e 9 . . . . . . . . . . . . . . . 
        9 9 9 . . . e e 9 8 9 9 9 9 9 9 9 9 9 9 9 9 9 . 
        9 9 9 9 e e e e 9 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
        9 9 9 . . . e e 9 8 9 9 9 9 9 9 9 9 9 9 9 9 9 . 
        . . . . . . . e 9 . . . . . . . . . . . . . . . 
        . . . . . . . 9 9 9 . . . . . . . . . . . . . . 
        . . . . . . . 9 6 9 . . . . . . . . . . . . . . 
        . . . . . . . 9 9 9 . . . . . . . . . . . . . . 
        `, SpriteKind.épé)
    épé_Arlem.follow(Arlem, 1000)
})
controller.down.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, Arlem)
    Arlem.setImage(img`
        .......22eee.......
        .....2222eeeee.....
        ....22222eeeeee....
        ...222222222eeee...
        ...2222222dd22ee...
        ...222228dd88dee...
        ...222288dd88d2e...
        9992222dddddddd2...
        969a2dddddddddd2...
        999a.dddffffddd....
        .aaaadddddddddd....
        ..aaffffffffffff...
        ..affffffffffffff..
        ..ffffffffffffffff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..affffffffffffaff.
        ..dddffffffffffddd.
        .....afffffffff889.
        .....afff..faff8889
        .....aff....aff9889
        .....aff....aff.999
        .....aff....aff....
        .....aff....aff....
        .....aff....aff....
        .....aff....aff....
        .....111....111....
        `)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Arlem,
    [img`
        . . . . . . . . . . . 
        . . . 2 e e e e . . . 
        . . 2 2 2 e e e e . . 
        . . 2 2 2 2 e 2 e . . 
        . . a 2 2 2 2 d 2 2 . 
        . . a 2 2 d d 8 d . . 
        . . a 2 d d d d d . . 
        . a a 2 d d d d d . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f a f f . . 
        . 9 8 f f f f a f . . 
        . 9 8 f f f f a f . . 
        . a a f f f f f a . . 
        . 9 8 f f f f f d . . 
        . 9 8 f f f d d f . . 
        . 9 8 f f f f f a . . 
        . 9 8 f f f f f f a . 
        . 8 8 f f a f f f a . 
        . . . f f a f f f a . 
        . . . f f a . f f a . 
        . . . f f a . f f a . 
        . . . f f a . 1 1 1 . 
        . . . 1 1 1 . . . . . 
        . . . . . . . . . . . 
        . . . . . . . . . . . 
        `,img`
        . . . 2 e e e e . . . 
        . . 2 2 2 e e e e . . 
        . . 2 2 2 2 e 2 e . . 
        . . a 2 2 2 2 d 2 2 . 
        . . a 2 2 d d 8 d . . 
        . . a 2 d d d d d . . 
        . a a 2 d d d d d . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f a f . . 
        . 9 8 f f f f f a . . 
        . 9 8 f f f f f a . . 
        . 9 8 f f f f f f a . 
        . a a f f f f f f d . 
        . 9 8 f f f f d d . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f a . 
        . 9 8 f f f f f f f a 
        . 8 8 f f f f f f f a 
        . . . f f f f . f f a 
        . . f f f f . . f f a 
        . . f f f f . . 1 1 1 
        . . f f f . . . . . . 
        . . 1 1 1 . . . . . . 
        . . . . . . . . . . . 
        . . . . . . . . . . . 
        `,img`
        . . . 2 e e e e . . . 
        . . 2 2 2 e e e e . . 
        . . 2 2 2 2 e 2 e . . 
        . . a 2 2 2 2 d 2 2 . 
        . . a 2 2 d d 8 d . . 
        . . a 2 d d d d d . . 
        . a a 2 d d d d d . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f a f f . . 
        . 9 8 f f f f a f . . 
        . 9 8 f f f f a f . . 
        . a a f f f f f a . . 
        . 9 8 f f f f f d . . 
        . 9 8 f f f d d f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f a . . 
        . 9 8 f f f f f f a . 
        . 8 8 f f a f f f a . 
        . . . f f a f f f a . 
        . . . f f a . f f a . 
        . . . f f a . f f a . 
        . . . f f a . 1 1 1 . 
        . . . 1 1 1 . . . . . 
        . . . . . . . . . . . 
        . . . . . . . . . . . 
        `,img`
        . . . 2 e e e e . . . 
        . . 2 2 2 e e e e . . 
        . . 2 2 2 2 e 2 e . . 
        . . a 2 2 2 2 d 2 2 . 
        . . a 2 2 d d 8 d . . 
        . . a 2 d d d d d . . 
        . a a 2 d d d d d . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f d d d f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 8 8 . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . 1 1 1 1 . . . 
        . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . 
        . . . 2 e e e e . . . 
        . . 2 2 2 e e e e . . 
        . . 2 2 2 2 e 2 e . . 
        . . a 2 2 2 2 d 2 2 . 
        . . a 2 2 d d 8 d . . 
        . . a 2 d d d d d . . 
        . a a 2 d d d d d . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f a f f . . 
        . 9 8 f f f a f f . . 
        . 9 8 f f f a f f . . 
        . a a f f a f f f . . 
        . 9 8 d f a f f f . . 
        . 9 8 f d d f f f . . 
        . 9 8 f f f f f a . . 
        . 9 8 f f f f f f a . 
        . 8 8 f f a f f f a . 
        . . . f f a f f f a . 
        . . . f f a . f f a . 
        . . . f f a . f f a . 
        . . . f f a . 1 1 1 . 
        . . . 1 1 1 . . . . . 
        . . . . . . . . . . . 
        . . . . . . . . . . . 
        `,img`
        . . . 2 e e e e . . . 
        . . 2 2 2 e e e e . . 
        . . 2 2 2 2 e 2 e . . 
        . . a 2 2 2 2 d 2 2 . 
        . . a 2 2 d d 8 d . . 
        . . a 2 d d d d d . . 
        . a a 2 d d d d d . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f a f f . . 
        . 9 8 f f f a f f . . 
        . 9 8 f f f a f f . . 
        . 9 8 f f a f f f . . 
        . a d f f a f f f . . 
        . 9 8 d d f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f a . 
        . 9 8 f f f f f f f a 
        . 8 8 f f f f f f f a 
        . . . f f f f . f f a 
        . . f f f f . . f f a 
        . . f f f f . . 1 1 1 
        . . f f f . . . . . . 
        . . 1 1 1 . . . . . . 
        . . . . . . . . . . . 
        . . . . . . . . . . . 
        `,img`
        . . . 2 e e e e . . . 
        . . 2 2 2 e e e e . . 
        . . 2 2 2 2 e 2 e . . 
        . . a 2 2 2 2 d 2 2 . 
        . . a 2 2 d d 8 d . . 
        . . a 2 d d d d d . . 
        . a a 2 d d d d d . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f a f f . . 
        . 9 8 f f f a f f . . 
        . 9 8 f f f a f f . . 
        . a a f f a f f f . . 
        . 9 8 d f a f f f . . 
        . 9 8 f d d f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f a . . 
        . 9 8 f f f f f f a . 
        . 8 8 f f a f f f a . 
        . . . f f a f f f a . 
        . . . f f a . f f a . 
        . . . f f a . f f a . 
        . . . f f a . 1 1 1 . 
        . . . 1 1 1 . . . . . 
        . . . . . . . . . . . 
        . . . . . . . . . . . 
        `,img`
        . . . 2 e e e e . . . 
        . . 2 2 2 e e e e . . 
        . . 2 2 2 2 e 2 e . . 
        . . a 2 2 2 2 d 2 2 . 
        . . a 2 2 d d 8 d . . 
        . . a 2 d d d d d . . 
        . a a 2 d d d d d . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . a a f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f d d d f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 9 8 f f f f f f . . 
        . 8 8 . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . f f f f . . . 
        . . . . 1 1 1 1 . . . 
        . . . . . . . . . . . 
        `],
    110,
    controller.right.isPressed()
    )
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    game.showLongText("ah te voici Zarlenem", DialogLayout.Bottom)
    game.showLongText("mon frère que fais-tu ici je te cherchais", DialogLayout.Bottom)
    tiles.setCurrentTilemap(tilemap`niveau6`)
    tiles.placeOnTile(Zarlenem, tiles.getTileLocation(29, 31))
    tiles.placeOnTile(Arlem, tiles.getTileLocation(25, 31))
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, Arlem)
    Arlem.setImage(img`
        . . . e e e e 2 . . . 
        . . e e e e 2 2 2 . . 
        . . e 2 e 2 2 2 2 . . 
        . 2 2 d 2 2 2 2 a . . 
        . . d 8 d d 2 2 a . . 
        . . d d d d d 2 a . . 
        . . d d d d d 2 a a . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f a f f f f 8 9 . 
        . . f a f f f f 8 9 . 
        . . f a f f f f 8 9 . 
        . . f a f f f f a a . 
        . . f a f f f f 8 9 . 
        . . f d d d f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . . f f f f . 8 8 . 
        . . . f f f f . . . . 
        . . . f f f f . . . . 
        . . . f f f f . . . . 
        . . . f f f f . . . . 
        . . . f f f f . . . . 
        . . . 1 1 1 1 . . . . 
        `)
})
controller.anyButton.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, Arlem)
})
sprites.onDestroyed(SpriteKind.Enemy, function (sprite) {
    mySprite3 = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................bbbbb...........
        ................bbbbb...........
        ................b9b9b...........
        .............88.bbbbb...........
        ............8998bbbbb...........
        ........c...8998bbbbbb..........
        ........c....8bb98bbbb9.........
        ........c....bbbbbabb9bb........
        ........c....bbbbbba9bbbb.......
        ........cccab..bbbbab8bbbccc....
        .......caccc9b...bbbbabbbcccc...
        .......accccabbb.bbbb8bbbcccc...
        .......caccababb.bbbb8bbbcccc...
        ........c9ac8bbb..8bbb8bb.9cc...
        .........cc.b8bbb.bbb8b8b.ca8c..
        .........8c.9bbbb.bbbbaba..ac8..
        .........9c8babbb..bab......a98.
        .....c8cc.bbbb88bbb..bb......89.
        .....cccc.bbb...bbb....b........
        .....cccc.abb8..bbb....b........
        .....ccc..bb8b..9b..b..bb.......
        ..........b9bbb.b9......b.......
        ..........bb9bb.bbbab...bb......
        `, SpriteKind.Player)
    tiles.placeOnTile(mySprite3, tiles.getTileLocation(32, 32))
    mySprite4 = sprites.create(img`
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        `, SpriteKind.teleporteur)
    tiles.placeOnTile(mySprite4, tiles.getTileLocation(31, 31))
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Arlem,
    [img`
        . . . . . . . . . . . 
        . . . e e e e 2 . . . 
        . . e e e e 2 2 2 . . 
        . . e 2 e 2 2 2 2 . . 
        . 2 2 d 2 2 2 2 a . . 
        . . d 8 d d 2 2 a . . 
        . . d d d d d 2 a . . 
        . . d d d d d 2 a a . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f a f f f f 8 9 . 
        . . f a f f f f 8 9 . 
        . . a f f f f f a a . 
        . . d f f f f f 8 9 . 
        . . f d d f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . a a f f f f f 8 9 . 
        . a f f f a f f 8 8 . 
        . a f f f a f f . . . 
        . a f f . a f f . . . 
        . a f f . a f f . . . 
        . 1 1 1 . a f f . . . 
        . . . . . 1 1 1 . . . 
        . . . . . . . . . . . 
        `,img`
        . . . e e e e 2 . . . 
        . . e e e e 2 2 2 . . 
        . . e 2 e 2 2 2 2 . . 
        . 2 2 d 2 2 2 2 a . . 
        . . d 8 d d 2 2 a . . 
        . . d d d d d 2 a . . 
        . . d d d d d 2 a a . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f a f f f f 8 9 . 
        . . a f f f f f 8 9 . 
        . . a f f f f f 8 9 . 
        . a f f f f f f 8 9 . 
        . d f f f f f f a a . 
        . . d d f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . a f f f f f f 8 9 . 
        a f f f f f f f 8 9 . 
        a f f f f f f f 8 8 . 
        a f f . f f f f . . . 
        a f f . . f f f f . . 
        1 1 1 . . f f f f . . 
        . . . . . . f f f . . 
        . . . . . . 1 1 1 . . 
        . . . . . . . . . . . 
        `,img`
        . . . e e e e 2 . . . 
        . . e e e e 2 2 2 . . 
        . . e 2 e 2 2 2 2 . . 
        . 2 2 d 2 2 2 2 a . . 
        . . d 8 d d 2 2 a . . 
        . . d d d d d 2 a . . 
        . . d d d d d 2 a a . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f a f f f f 8 9 . 
        . . f a f f f f 8 9 . 
        . . a f f f f f a a . 
        . . d f f f f f 8 9 . 
        . . f d d f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . a f f f f f 8 9 . 
        . a f f f f f f 8 9 . 
        . a f f f a f f 8 8 . 
        . a f f f a f f . . . 
        . a f f . a f f . . . 
        . a f f . a f f . . . 
        . 1 1 1 . a f f . . . 
        . . . . . 1 1 1 . . . 
        . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . 
        . . . e e e e 2 . . . 
        . . e e e e 2 2 2 . . 
        . . e 2 e 2 2 2 2 . . 
        . 2 2 d 2 2 2 2 a . . 
        . . d 8 d d 2 2 a . . 
        . . d d d d d 2 a . . 
        . . d d d d d 2 a a . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f d d d f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 8 . 
        . . . a f f f . . . . 
        . . . a f f f . . . . 
        . . . a f f f . . . . 
        . . . a f f f . . . . 
        . . . a f f f . . . . 
        . . . 1 1 1 1 . . . . 
        `,img`
        . . . e e e e 2 . . . 
        . . e e e e 2 2 2 . . 
        . . e 2 e 2 2 2 2 . . 
        . 2 2 d 2 2 2 2 a . . 
        . . d 8 d d 2 2 a . . 
        . . d d d d d 2 a . . 
        . . d d d d d 2 a a . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f f f a f f a a . 
        . . f f f a f d 8 9 . 
        . . f f f d d f 8 9 . 
        . . f f f f f f 8 9 . 
        . . a f f f f f 8 9 . 
        . a f f f f f f 8 9 . 
        . a f f f a f f 8 8 . 
        . a f f f a f f . . . 
        . a f f . a f f . . . 
        . a f f . a f f . . . 
        . 1 1 1 . a f f . . . 
        . . . . . 1 1 1 . . . 
        . . . . . . . . . . . 
        `,img`
        . . . e e e e 2 . . . 
        . . e e e e 2 2 2 . . 
        . . e 2 e 2 2 2 2 . . 
        . 2 2 d 2 2 2 2 a . . 
        . . d 8 d d 2 2 a . . 
        . . d d d d d 2 a . . 
        . . d d d d d 2 a a . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f f f a f f 8 9 . 
        . . f f f a f f d a . 
        . . f f f f d d 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . a f f f f f f 8 9 . 
        a f f f f f f f 8 9 . 
        a f f f f f f f 8 8 . 
        a f f . f f f f . . . 
        a f f . . f f f f . . 
        1 1 1 . . f f f f . . 
        . . . . . . f f f . . 
        . . . . . . 1 1 1 . . 
        . . . . . . . . . . . 
        `,img`
        . . . e e e e 2 . . . 
        . . e e e e 2 2 2 . . 
        . . e 2 e 2 2 2 2 . . 
        . 2 2 d 2 2 2 2 a . . 
        . . d 8 d d 2 2 a . . 
        . . d d d d d 2 a . . 
        . . d d d d d 2 a a . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f f a f f f 8 9 . 
        . . f f f a f f a a . 
        . . f f f a f d 8 9 . 
        . . f f f d d f 8 9 . 
        . . f f f f f f 8 9 . 
        . . a f f f f f 8 9 . 
        . a f f f f f f 8 9 . 
        . a f f f a f f 8 8 . 
        . a f f f a f f . . . 
        . a f f . a f f . . . 
        . a f f . a f f . . . 
        . 1 1 1 . a f f . . . 
        . . . . . 1 1 1 . . . 
        . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . 
        . . . e e e e 2 . . . 
        . . e e e e 2 2 2 . . 
        . . e 2 e 2 2 2 2 . . 
        . 2 2 d 2 2 2 2 a . . 
        . . d 8 d d 2 2 a . . 
        . . d d d d d 2 a . . 
        . . d d d d d 2 a a . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f a a . 
        . . f f f f f f 8 9 . 
        . . f d d d f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 9 . 
        . . f f f f f f 8 8 . 
        . . . a f f f . . . . 
        . . . a f f f . . . . 
        . . . a f f f . . . . 
        . . . a f f f . . . . 
        . . . a f f f . . . . 
        . . . 1 1 1 1 . . . . 
        `],
    110,
    controller.left.isPressed()
    )
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    tiles.setCurrentTilemap(tilemap`niveau3`)
    scene.cameraShake(10, 2000)
    game.showLongText("Vous ressentez une force qui modifie la carte ", DialogLayout.Bottom)
    game.showLongText("Trouve le cristal magique pour vaincre le gardien", DialogLayout.Bottom)
    cristal = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . 8 . . . . . . . 
        . . . . . . . 8 9 8 . . . . . . 
        . . . . . . . 8 9 8 . . . . . . 
        . . . . . . 8 9 9 8 8 . . . . . 
        . . . . . . 8 9 8 8 8 . . . . . 
        . . . . . . 8 9 8 8 8 . . . . . 
        . . . . . . 8 9 8 8 8 . . . . . 
        . . 8 8 . . 8 9 8 8 8 . . . . . 
        . . 8 9 8 . 8 9 8 8 8 . . 8 8 . 
        . . 8 8 9 8 8 9 8 8 8 . 8 9 8 . 
        . . . 8 8 9 8 9 8 8 8 8 9 8 8 . 
        . . . 8 8 8 8 9 8 8 8 9 8 8 . . 
        . . . . . 8 8 9 8 8 8 8 8 . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.object)
    tiles.placeOnRandomTile(cristal, assets.tile`myTile0`)
})
let cristal: Sprite = null
let mySprite4: Sprite = null
let mySprite3: Sprite = null
let épé_Arlem: Sprite = null
let myMinimap: minimap.Minimap = null
let statusbar: StatusBarSprite = null
let Zarlenem: Sprite = null
let mapSprite: Sprite = null
let Arlem: Sprite = null
music.play(music.createSong(assets.song`mySong`), music.PlaybackMode.LoopingInBackground)
tiles.setTilemap(tilemap`niveau1`)
Arlem = sprites.create(img`
    .......22eee.......
    .....2222eeeee.....
    ....22222eeeeee....
    ...222222222eeee...
    ...2222222dd22ee...
    ...222228dd88dee...
    ...222288dd88d2e...
    9992222ddddddddf...
    96922dddddddddd2...
    9992.dddffffddd....
    .2222dddddddddd....
    ..22ffffffffffff...
    ..2ffffffffffffff..
    ..ffffffffffffffff.
    ..ffffffffffffffff.
    ..afffffffffffffff.
    ..afffffffffffffff.
    ..afffffffffffffff.
    ..afffffffffffffff.
    ..aaffffffffffffff.
    ..dddffffffffffddd.
    .....afffffffff889.
    .....affb..baff8889
    .....aff....aff9889
    .....aff....aff.999
    .....aff....aff....
    .....aff....aff....
    .....aff....aff....
    .....aaa....aaf....
    .....111....111....
    `, SpriteKind.Player)
let mySprite2 = sprites.create(img`
    ................................
    ................................
    .............bbbbb..............
    .............bbbbb..............
    .............b9b9b..............
    ..........88.bbbbb..............
    .........8998bbbbb..............
    .........8998bbbbbb.............
    ..........8bb98bbbb9............
    ..........bbbbbabb9bb...........
    .........bbbbbbba9bbbb..........
    ......ccabbbbbbbab8bbbccc.......
    .....cccc9bbbbbbbbabbbcccc......
    .....ccccabbbbbbbb8bbbccccc.....
    ....cc8cababbbbbbb8bbbcccca9....
    ....c9cac8bbbbb8bbb8bb...c9c8...
    ....cc9c.b8bbbabbb8b8b....ca8c..
    ....c8cc.9bbbb9bbbbaba.....ac8..
    ....c9c8..bbbabbbbbba.......a98.
    ...cac8cc..bbb88bbbb.........89.
    ...accccc...b.....b.............
    ...cacccc..bb8...abb............
    ....cccc...b8b...bab............
    ...........9bb...b8b............
    ...........9ba...abb............
    ...........b9b...b8b............
    ..........babbb.b9bbb...........
    ..........bbbb8.bbbba...........
    ..........abbb8.bbb8b...........
    ..........bab9b.9bb8b...........
    ..........bb9bb.b99b8...........
    ..........bb9bb.bbbab...........
    `, SpriteKind.Enemy)
controller.moveSprite(Arlem)
scene.cameraFollowSprite(Arlem)
tiles.placeOnTile(Arlem, tiles.getTileLocation(3, 3))
tiles.placeOnTile(mySprite2, tiles.getTileLocation(29, 31))
mapSprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Projectile)
mapSprite.setPosition(7, 8)
